- name: update apt packages
  apt:
    update_cache: yes
  become: true

- name: install dependincies
  apt:
    name:
      - prometheus
      - libfontconfig1
    state: present
    update_cache: yes
  become: true

- name: Download grafana deb
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_6.3.2_amd64.deb
    dest: "{{  path_workdir  }}/grafana_6.3.2_amd64.deb"

- name: dpkg grafana
  command:
    chdir: "{{  path_workdir  }}"
    cmd:  /usr/bin/dpkg -i grafana_6.3.2_amd64.deb
  become: true
  notify: 
  - deamon reload
  - Start grafana service