- name: clone project
  ansible.builtin.git:
    repo: "{{ git_repository }}{{ project }}.git"
    dest: "{{  git_folder }}"
  become: true

- name: Create Dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{  git_folder }}/Dockerfile"
  become: true

- name: docker build
  command:
    chdir: "{{  git_folder }}"
    cmd:  /usr/bin/docker build -t "{{ registry_name }}/{{ item }}":latest .
  become: true

- name: Deleted directory
  file:
    state: absent
    path: "{{  git_folder  }}"
  become: true